CREATE DATABASE VIRTUALMANAGEMENT;
USE VIRTUALMANAGEMENT;

CREATE TABLE USERS (
    USER_ID INT PRIMARY KEY,
    USERNAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(10) NOT NULL
);

DESCRIBE USERS;
SELECT * FROM USERS;
 
CREATE TABLE EXPERIENCE (
    EXPERIENCES_ID INT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    CATEGORY VARCHAR(50)
);

SELECT * FROM EXPERIENCE;
DESCRIBE EXPERIENCE;
 
CREATE TABLE SESSIONS (
    SESSION_ID INT PRIMARY KEY,
    USER_ID INT,
    SESSION_DATE VARCHAR(20),
    STATUS VARCHAR(20),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
);
 
 DESCRIBE SESSIONS;
 SELECT * FROM SESSIONS;
 
CREATE TABLE FEEDBACK (
    FEEDBACK_ID INT,
    USER_ID INT,
    SESSION_ID INT,
    RATING INT CHECK(rating >= 1 AND rating <= 5),
    CREATED_DATE VARCHAR(20),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
    FOREIGN KEY (SESSION_ID) REFERENCES Sessions(SESSION_ID)
);

DESCRIBE FEEDBACK;
SELECT * FROM FEEDBACK;

-INSERT VALUES FOR USERS-----;

INSERT INTO USERS (USER_ID,USERNAME,EMAIL,PASSWORD) VALUES(101,'MADHAVAN','maddy@gmail.com','1234');
INSERT INTO USERS (USER_ID,USERNAME,EMAIL,PASSWORD) VALUES(102,'MUKESH','mukesh@gmail.com','5678');
INSERT INTO USERS (USER_ID,USERNAME,EMAIL,PASSWORD) VALUES(103,'ARUL','arul@gmail.com','1234');
INSERT INTO USERS (USER_ID,USERNAME,EMAIL,PASSWORD) VALUES(104,'RISHI','rishi@gmail.com','8924');
INSERT INTO USERS (USER_ID,USERNAME,EMAIL,PASSWORD) VALUES(105,'RAJESH','raj@gmail.com','78923');
INSERT INTO USERS (USER_ID,USERNAME,EMAIL,PASSWORD) VALUES(106,'TERRANCE','terrance@gmail.com','89344');
INSERT INTO USERS (USER_ID,USERNAME,EMAIL,PASSWORD) VALUES(107,'RANJITH','ranjith@gmail.com','1234');

-INSERT VALUES FOR EXPERIENCE-----;

INSERT INTO EXPERIENCE (EXPERIENCES_ID,TITLE,DESCRIPTION,CATEGORY) VALUES(201,'XXXXXXX','XXXXX','XXXX');
INSERT INTO EXPERIENCE (EXPERIENCES_ID,TITLE,DESCRIPTION,CATEGORY) VALUES(202,'XXXXXXX','XXXXX','XXXX');
INSERT INTO EXPERIENCE (EXPERIENCES_ID,TITLE,DESCRIPTION,CATEGORY) VALUES(203,'XXXXXXX','XXXXX','XXXX');
INSERT INTO EXPERIENCE (EXPERIENCES_ID,TITLE,DESCRIPTION,CATEGORY) VALUES(204,'XXXXXXX','XXXXX','XXXX');
INSERT INTO EXPERIENCE (EXPERIENCES_ID,TITLE,DESCRIPTION,CATEGORY) VALUES(205,'XXXXXXX','XXXXX','XXXX');
INSERT INTO EXPERIENCE (EXPERIENCES_ID,TITLE,DESCRIPTION,CATEGORY) VALUES(206,'XXXXXXX','XXXXX','XXXX');
INSERT INTO EXPERIENCE (EXPERIENCES_ID,TITLE,DESCRIPTION,CATEGORY) VALUES(207,'XXXXXXX','XXXXX','XXXX');

-INSERT VALUES FOR SESSION-----;

INSERT INTO SESSIONS(SESSION_ID,USER_ID,SESSION_DATE,STATUS) VALUES(301,'103','XXXXX','XXXX');
INSERT INTO SESSIONS(SESSION_ID,USER_ID,SESSION_DATE,STATUS) VALUES(302,'102','XXXXX','XXXX');
INSERT INTO SESSIONS(SESSION_ID,USER_ID,SESSION_DATE,STATUS) VALUES(303,'105','XXXXX','XXXX');
INSERT INTO SESSIONS(SESSION_ID,USER_ID,SESSION_DATE,STATUS) VALUES(304,'101','XXXXX','XXXX');
INSERT INTO SESSIONS(SESSION_ID,USER_ID,SESSION_DATE,STATUS) VALUES(305,'104','XXXXX','XXXX');
INSERT INTO SESSIONS(SESSION_ID,USER_ID,SESSION_DATE,STATUS) VALUES(306,'106','XXXXX','XXXX');
INSERT INTO SESSIONS(SESSION_ID,USER_ID,SESSION_DATE,STATUS) VALUES(307,'107','XXXXX','XXXX');

-INSERT VALUES FOR FEEDBACK-----;

INSERT INTO FEEDBACK(FEEDBACK_ID,USER_ID,SESSION_ID,RATING,CREATED_DATE) 
VALUES(401,'107','307','4','XXXXXX');

INSERT INTO FEEDBACK(FEEDBACK_ID,USER_ID,SESSION_ID,RATING,CREATED_DATE) 
VALUES(402,'106','306','4','XXXXX');

INSERT INTO FEEDBACK(FEEDBACK_ID,USER_ID,SESSION_ID,RATING,CREATED_DATE) 
VALUES(403,104,'305','3','XXXXXX');

INSERT INTO FEEDBACK(FEEDBACK_ID,USER_ID,SESSION_ID,RATING,CREATED_DATE) 
VALUES(404,101,'304','1','XXXXXX');

INSERT INTO FEEDBACK(FEEDBACK_ID,USER_ID,SESSION_ID,RATING,CREATED_DATE) 
VALUES(405,105,'303','3','XXXXXX');

INSERT INTO FEEDBACK(FEEDBACK_ID,USER_ID,SESSION_ID,RATING,CREATED_DATE) 
VALUES(406,102,'302','5','XXXXXX');

INSERT INTO FEEDBACK(FEEDBACK_ID,USER_ID,SESSION_ID,RATING,CREATED_DATE) 
VALUES(407,103,'301','4','XXXXXX' );
