// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageConnectorService.Data;

#nullable disable

namespace StorageConnectorService.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250710061743_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StorageConnectorService.Model.StorageConnector", b =>
                {
                    b.Property<int>("StorageConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StorageConnectorId"));

                    b.Property<string>("StorageConnectorDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StorageConnectorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StorageConnectorId");

                    b.ToTable("StorageConnectors");
                });
#pragma warning restore 612, 618
        }
    }
}
