create database PARKING;
USE PARKING;

CREATE TABLE CUSTOMERS(
CUSTOMERID INT PRIMARY KEY, 
CUSTOMERNAME VARCHAR(40),
CUSTOMERAGE INT,
CUSTOMERGENDER VARCHAR(40));

INSERT INTO CUSTOMERS VALUES (101,"JOHN",26,"MALE");
INSERT INTO CUSTOMERS VALUES (102,"KUMAR",32,"MALE");
INSERT INTO CUSTOMERS VALUES (103,"RAJESH",28,"MALE");
INSERT INTO CUSTOMERS VALUES (104,"RAMESH",24,"MALE");
INSERT INTO CUSTOMERS VALUES (105,"CHRIS",29,"MALE");

describe customers;

SELECT *FROM CUSTOMERS;

CREATE TABLE ADDRESS(
ADDRESSID INT PRIMARY KEY,
ADDRESS VARCHAR(40),
CUSTOMERID INT,
FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID));

INSERT INTO ADDRESS VALUES(90,"CHENNAI",101);
INSERT INTO ADDRESS VALUES(91,"TRICHY",102);
INSERT INTO ADDRESS VALUES(92,"MADURAI",103);
INSERT INTO ADDRESS VALUES(93,"VIRUDHUNAGAR",104);
INSERT INTO ADDRESS VALUES(94,"KERALA",105);


DROP TABLE CUSTOMERS;


SELECT *FROM ADDRESS;

UPDATE address set address=coimbatore where addressid=91;

select c.customername, a.address from customers c left join address a on customerid=customerid;

select customername FROM CUSTOMERS CUSTOMERDETAILS UNION SELECT ADDRESSID FROM ADDRESS AS DETAILS;

DROP TABLE VEHICLE;

CREATE TABLE VEHICLE(
VEHICLEID INT PRIMARY KEY,
VEHICLENAME VARCHAR(40),
ADDRESSID INT,
FOREIGN KEY (ADDRESSID) REFERENCES ADDRESS(ADDRESSID));


DESCRIBE VEHICLE;

insert INTO VEHICLE VALUES (200,"BMW",90);
insert INTO VEHICLE VALUES (201,"BMW-BIKE",91);
insert INTO VEHICLE VALUES (202,"XL",92);
insert INTO VEHICLE VALUES (203,"FZ",93);
insert INTO VEHICLE VALUES (204,"PULSAR",94);

SELECT *FROM VEHICLE;

SELECT V.VEHICLENAME, ADDRESS FROM VEHICLE V JOIN ADDRESS A ON ADDRESSID=ADDRESSID;
DROP TABLE VEHICLE;



CREATE TABLE PARKING( 
PARKINGID int,
 PARKINGTIME VARCHAR(30), 
 PARKINGDATE VARCHAR(30));
 
 insert into parking values(1,"6:30","2/2/2025");
 insert into parking values(2,"3:00","6/03/2025");
 insert into parking values(3,"6:44","8/05/2025");
 insert into parking values(4,"5:30","10/06/2025");
 insert into parking values(5,"6:30","4/2/2025");
 
 UPDATE PARKING SET PARKINGTIME = "9:25" WHERE PARKINGID=5;
 
 DELETE FROM PARKING WHERE PARKINGID=5;
 
 
 select count(*) from parking;

SELECT vehiclename, COUNT(*) AS vehicle_count
FROM vehicle
GROUP BY vehicleid;

select * from customers where customerage>30;