CREATE DATABASE WASTE_MANAGEMENT;

USE WASTE_MANAGEMENT;

CREATE TABLE USER (
USER_ID INT PRIMARY KEY,
USER_NAME VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(50),
WASTE_QUANTITY INT,
EMPLOYEE_ID INT,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) 
);

INSERT INTO USER VALUES (1,'Rajesh','Bank street',5,2),(2,'Dony','Car street',7,1),(3,'Ajith','mayil street',12,1),(4,'Suresh','palace street',9,3);
INSERT INTO USER VALUES (5,'Sanjay','Kotak street',5,4),(6,'Abi','Bye pass street',11,2),(7,'Varun','kk street',3,6),(8,'Rajkumar','burkit street',4,7);

UPDATE USER SET USER_NAME = 'Abishek' WHERE USER_NAME = 'Abi';


SELECT * FROM USER;
DROP TABLE USER;

CREATE TABLE EMPLOYEES (
EMPLOYEE_ID INT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(30) NOT NULL,
EXPERIENCE INT,
CONSTRAINT C1 CHECK (EXPERIENCE > 2)
);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME , EXPERIENCE) VALUES (1,'Kavin', 4);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME , EXPERIENCE) VALUES (2,'Prem', 7);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME , EXPERIENCE) VALUES (3,'Akil', 8);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME , EXPERIENCE) VALUES (4,'Anu', 3);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME , EXPERIENCE) VALUES (5,'Aswin', 6);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME , EXPERIENCE) VALUES (6,'Arun', 9);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME , EXPERIENCE) VALUES (7,'Akash', 7);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME , EXPERIENCE) VALUES (8,'Naveen', 5);

SELECT * FROM EMPLOYEES;

DROP TABLE EMPLOYEES;


CREATE TABLE RECYCLE (
PRODUCT_ID INT PRIMARY KEY,
USER_ID INT,
PRODUCT_NAME VARCHAR(50),
RECYCLE_QUANTITY INT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
CONSTRAINT C2 CHECK(RECYCLE_QUANTITY > 2)
);

INSERT INTO RECYCLE (PRODUCT_ID, USER_ID, PRODUCT_NAME, RECYCLE_QUANTITY) VALUES (1,5,'scrap',10);
INSERT INTO RECYCLE (PRODUCT_ID, USER_ID, PRODUCT_NAME, RECYCLE_QUANTITY) VALUES (2,3,'paper',20);
INSERT INTO RECYCLE (PRODUCT_ID, USER_ID, PRODUCT_NAME, RECYCLE_QUANTITY) VALUES (3,1,'metal',9);
INSERT INTO RECYCLE (PRODUCT_ID, USER_ID, PRODUCT_NAME, RECYCLE_QUANTITY) VALUES (4,4,'wood',22);
INSERT INTO RECYCLE (PRODUCT_ID, USER_ID, PRODUCT_NAME, RECYCLE_QUANTITY) VALUES (5,8,'tank',7);
INSERT INTO RECYCLE (PRODUCT_ID, USER_ID, PRODUCT_NAME, RECYCLE_QUANTITY) VALUES (6,7,'marble',16);
INSERT INTO RECYCLE (PRODUCT_ID, USER_ID, PRODUCT_NAME, RECYCLE_QUANTITY) VALUES (7,6,'chalk',3);
INSERT INTO RECYCLE (PRODUCT_ID, USER_ID, PRODUCT_NAME, RECYCLE_QUANTITY) VALUES (8,2,'tile',11);

SELECT * FROM RECYCLE;

CREATE TABLE ADMIN (
USER_ID INT ,
EMPLOYEE_ID INT,
PRODUCT_ID INT,
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES RECYCLE(PRODUCT_ID)
);

INSERT INTO ADMIN ( USER_ID, EMPLOYEE_ID, PRODUCT_ID) VALUES ( 5, 4, 1);
INSERT INTO ADMIN ( USER_ID, EMPLOYEE_ID, PRODUCT_ID) VALUES ( 1, 2, 3);
INSERT INTO ADMIN ( USER_ID, EMPLOYEE_ID, PRODUCT_ID) VALUES ( 3, 1, 2);
INSERT INTO ADMIN ( USER_ID, EMPLOYEE_ID, PRODUCT_ID) VALUES ( 5, 4, 1);
INSERT INTO ADMIN ( USER_ID, EMPLOYEE_ID, PRODUCT_ID) VALUES ( 6, 2, 7);
INSERT INTO ADMIN ( USER_ID, EMPLOYEE_ID, PRODUCT_ID) VALUES ( 7, 6, 6);
INSERT INTO ADMIN ( USER_ID, EMPLOYEE_ID, PRODUCT_ID) VALUES ( 8, 7, 5);

UPDATE ADMIN SET USER_ID = 7 WHERE PRODUCT_ID = 2;

SELECT * FROM ADMIN;

DELETE FROM ADMIN WHERE EMPLOYEE_ID = 4;



DROP TABLE ADMIN;

