CREATE DATABASE RELEVANTZ;

USE RELEVANTZ;

CREATE TABLE PRODUCTS(
	PID INT AUTO_INCREMENT PRIMARY KEY,
    PNAME VARCHAR(100),
    PDESCRIPTION TEXT,
    PPRICE DECIMAL(10,2)
);

SELECT * FROM PRODUCTS;