"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var submain_1 = require("./submain");
var p1 = document.getElementById('pid');
var p2 = document.getElementById('pname');
var p3 = document.getElementById('pprice');
var p4 = document.getElementById('pis');
var bu1 = document.getElementById('b1');
bu1.addEventListener('click', function (e) {
    e.preventDefault();
    var id = Number(p1.value);
    var name = p2.value;
    var price = Number(p3.value);
    var inStock = p4.checked;
    var p = new submain_1.ProductItem(id, name, price, inStock);
    p.dis();
});
var b1 = document.getElementById('bid');
var b2 = document.getElementById('bname');
var b3 = document.getElementById('bauthor');
var b4 = document.getElementById('bpages');
var bu2 = document.getElementById('b2');
bu2.addEventListener('click', function (e) {
    e.preventDefault();
    var id = Number(b1.value);
    var name = b2.value;
    var author = b3.value;
    var pages = Number(b4.value);
    var b = new submain_1.BookItem({ id: id, name: name, author: author, pages: pages });
    b.dis();
});
var c1 = document.getElementById('cid');
var c2 = document.getElementById('cname');
var c3 = document.getElementById('cmake');
var c4 = document.getElementById('cmodel');
var c5 = document.getElementById('cyear');
var c6 = document.getElementById('cis');
var bu3 = document.getElementById('b3');
bu3.addEventListener('click', function (e) {
    e.preventDefault();
    var id = Number(c1.value);
    var name = c2.value;
    var make = c3.value;
    var model = c4.value;
    var year = c5.value;
    var isRunning = c6.checked;
    var c = new submain_1.CarItem(id, name, make, model, year, isRunning);
    c.dis();
});
var e1 = document.getElementById('eid');
var e2 = document.getElementById('ename');
var e3 = document.getElementById('epos');
var e4 = document.getElementById('esalary');
var e5 = document.getElementById('eis');
var bu4 = document.getElementById('b4');
bu4.addEventListener('click', function (e) {
    e.preventDefault();
    var id = Number(e1.value);
    var name = e2.value;
    var position = e3.value;
    var salary = Number(e4.value);
    var isFullTime = e5.checked;
    var f = new submain_1.EmployeeItem(id, name, position, salary, isFullTime);
    f.dis();
});
var co1 = document.getElementById('coid');
var co2 = document.getElementById('coname');
var co3 = document.getElementById('coins');
var co4 = document.getElementById('codur');
var co5 = document.getElementById('cois');
var bu5 = document.getElementById('b5');
bu5.addEventListener('click', function (e) {
    e.preventDefault();
    var id = Number(co1.value);
    var name = co2.value;
    var instructor = co3.value;
    var duration = Number(co4.value);
    var isOnline = co5.checked;
    var c = new submain_1.CourseItem(id, name, instructor, duration, isOnline);
    c.dis();
});
